### ISSUE TITLE
Change Timezones via URL

### ISSUE THREAD

**Issue by JanOwiesniak** [hasinhayder/fifawc#1]
# Approach

```
http://fifawc.xyz?utc=+2
```

Should show the fixtures in the given timezone.

**Comment by hasinhayder** [comment]
It has been done and pushed :)
http://fifawc.xyz/?utc=-4
http://fifawc.xyz/?utc=2

:)

**Comment by JanOwiesniak** [comment]
Wow this was insanely fast 👍

Thanks!
